version: "3.8"

services:
  nginx:
    volumes:
      - ./data/shared_acme:/var/www/letsencrypt
    build:
      context: images/nginx
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - "80:80"

  certbot:
    build: images/certbot
    tty: true
    volumes:
      - ./data/shared_acme:/var/www/letsencrypt
      - ./data/archive_ssl:/etc/letsencrypt/archive